# Generated by Django 3.1 on 2022-01-12 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0006_auto_20220112_0927'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
